// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHt-Y9WB_9MdW54BRPJJ-rUlwMz6z-Ew4',
    appId: '1:197498952881:web:724d95ee2daccdbecc1690',
    messagingSenderId: '197498952881',
    projectId: 'tiket-wisata-dlundung',
    authDomain: 'tiket-wisata-dlundung.firebaseapp.com',
    storageBucket: 'tiket-wisata-dlundung.firebasestorage.app',
    measurementId: 'G-W8YC61VBQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Lz-DNNA7tc65vXQiHPGo_1hZKg1YQ90',
    appId: '1:197498952881:android:1ab303d3c48d60bccc1690',
    messagingSenderId: '197498952881',
    projectId: 'tiket-wisata-dlundung',
    storageBucket: 'tiket-wisata-dlundung.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhYqI0c2eVEexmVYP7EC-fgCN710YWoZ0',
    appId: '1:197498952881:ios:bb677d819086a73acc1690',
    messagingSenderId: '197498952881',
    projectId: 'tiket-wisata-dlundung',
    storageBucket: 'tiket-wisata-dlundung.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhYqI0c2eVEexmVYP7EC-fgCN710YWoZ0',
    appId: '1:197498952881:ios:bb677d819086a73acc1690',
    messagingSenderId: '197498952881',
    projectId: 'tiket-wisata-dlundung',
    storageBucket: 'tiket-wisata-dlundung.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHt-Y9WB_9MdW54BRPJJ-rUlwMz6z-Ew4',
    appId: '1:197498952881:web:e12ff388b21f7459cc1690',
    messagingSenderId: '197498952881',
    projectId: 'tiket-wisata-dlundung',
    authDomain: 'tiket-wisata-dlundung.firebaseapp.com',
    storageBucket: 'tiket-wisata-dlundung.firebasestorage.app',
    measurementId: 'G-LVSJXCNXWP',
  );
}
